CREATE TABLE dbo.users (
    id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_users PRIMARY KEY,
    username NVARCHAR(100) NOT NULL CONSTRAINT UQ_users_username UNIQUE,
    email NVARCHAR(255) NOT NULL,
    created_at DATETIME2 NOT NULL CONSTRAINT DF_users_created_at DEFAULT SYSUTCDATETIME()
);
